Gamegoo-repo/Gamegoo-socket-server

.github/workflows/dockerEC2.yml
dockerEC2.yml 주석 수정
- dockerEC2.yml 주석 수정
=> 📝 [Docs]: dockerEC2.yml 주석 수정

public/index.html
=> 💄 [style]: css 수정

.github/workflows/dockerEC2.yml, public/index.html
프로젝트 생성 및 cicd 연동
- 프로젝트 생성
- docker cicd 연동
=> [Feat/1] 프로젝트 생성 및 cicd 연동

.github/workflows/dockerEC2.yml, app/app.js, socket/socket.js
localhost:3000 CORS 허용 설정
- app.js에 cors 설정 추가
- socket.js에 cors 설정 추가
=> [Feat/7] CORS 설정

public/scripts/api.js
8080서버 api 요청 url 수정
- 요청 url endpoint /api -> /v1 으로 변경
=> ✨ [Feat] 8080서버 api 요청 url 수정

app/app.js, socket/socket.js
socket.gamegoo.co.kr 도메인 cors 허용
- cors origin 추가
=> 🐛 [Fix] socket 도메인 cors 허용

socket/apis/chatApi.js, socket/apis/friendApi.js
api 요청 axios로 변경
- api 요청 axios로 변경
=> 🐛 [Fix] api 요청 axios로 변경

app/app.js, public/scripts/api.js, public/scripts/eventListeners.js
친구 목록 입장 버튼 클릭 시 친구 목록 조회 및 화면 렌더링
- 친구 목록 입장 버튼 클릭 시 8080 서버에 친구 목록 조회 api 전송
- 친구 목록 화면 렌더링 및 친구 온라인 여부 표시
=> [Feat/22] 친구목록 조회 및 화면 렌더링

app/controller/logoutController.js, app/routers/index.js, public/scripts/eventListeners.js, public/scripts/socket.js, socket/emitters/friendEmitter.js, socket/socket.js
socket disconnect 및 로그아웃 관련 event 구현
- logout api 구현
- 로그아웃 버튼 클릭 시 3000 서버 /logout api 요청 전송
- socket disconnect 시 친구 목록 조회해 friend-offline event emit
- friend-offline event emitter & listener 구현
=> [Feat/24] socket disconnect 및 로그아웃 관련 event 구현

public/scripts/api.js, public/scripts/eventListeners.js
채팅방 목록 조회 및 채팅방 입장 기능 구현 
- 클라이언트 채팅방 목록 조회 api 요청 메소드 추가
- 클라이언트 채팅방 입장 api 요청 메소드 추가
- 클라이언트 채팅방 목록 버튼 클릭 listener 추가
- 클라이언트 채팅방 입장 버튼 클릭 listener 추가
- 채팅방 입장 api endpoint 변경
=> [Feat/26] 채팅방 목록 조회 및 채팅방 입장 기능 구현 

public/scripts/api.js, public/scripts/eventListeners.js
메시지 내역 조회 api 요청 및 렌더링
- 8080서버로 메시지 내역 조회 api 요청
- 응답 값을 화면에 렌더링
=> [Feat/30] 메시지 내역 조회 api 요청 및 렌더링

public/scripts/eventListeners.js, socket/apis/chatApi.js, socket/apis/friendApi.js, socket/handlers/chat/chatHandler.js, socket/socket.js
flow 주석 수정 및 에러처리 리팩토링
- flow 주석 수정
- 3000 -> 8080 api 호출 메소드 에러 처리 로직 수정
=> [Feat/30] flow 주석 수정 및 에러처리 리팩토링

app/app.js, public/scripts/eventListeners.js, public/styles.css
알림 버튼 추가 및 알림창 화면 구현
- 메인 헤더에 알림 버튼 추가
- 알림 버튼 클릭 시 알림 창 화면 구현, 알림 타입 및 읽음 여부 구분
=> [Feat/35] 알림 버튼 추가 및 알림창 화면 구현

app/controller/socketController.js, app/routers/index.js, public/scripts/eventListeners.js, public/scripts/socket.js, socket/emitters/chatEmitter.js, socket/handlers/chat/chatHandler.js
채팅방 room join API 및 room leave 구현
- 채팅방 room join API 추가
- "joined-new-chatroom" event 구현
- "exit-chatroom" event 구현
=> [Feat/43] 채팅방 room join API 및 room leave 구현

app/controller/loginController.js, app/controller/socketController.js, app/routers/index.js, public/scripts/eventListeners.js, public/scripts/socket.js, socket/handlers/chat/chatHandler.js, socket/handlers/chat/chatInitializer.js, socket/handlers/friend/friendInitializer.js
- 로그인 버튼 클릭 flow에서 나의 회원정보 API 요청 과정 제거
- 채팅방 입장/시작 시 화면 렌더링 부분 메소드 추가
- flow 주석 추가
=> [Refactor/45] 기존 코드 리팩토링 및 주석 추가

app/controller/socketController.js, app/routers/index.js, public/scripts/eventListeners.js, public/scripts/socket.js, socket/handlers/chat/chatHandler.js
Flow별 주석 추가 및 수정
- Flow별 주석 추가 및 수정
=> [Docs/50] Flow별 주석 추가 및 수정

socket/handlers/matching/matchingSocketListeners.js
matching-retry emit 로직 구현
- socket.myInfo 추가
- 2분 뒤 매칭 다시 잡히도록 변경
socket에 roomName과 myMatchingInfo를 저장했습니다. 그런데 myMatchingInfo를 굳이 저장해야하나라는 생각이 들고, 처음 들어왔을 때 저장하고 갱신하지 않아서 emitMatchingFoundReceiver 부를 때 해당 myMatchingInfo 정보를 사용해도 되는지 의문입니다. 이 myMatchingInfo를 8080에 API 한번 더 불러가면서 꼭 넘겨줘야하는지, 아니면 3000번에서 정보를 짜집기해서 보내도 괜찮은지 궁금합니다.
=> ✨ [Feat] matching_retry 구현

public/scripts/eventListeners.js
채팅방 새로 생성 시 채팅방 영역 렌더링 안되는 버그 수정
- 채팅방 영역 렌더링 메소드에서 result.chatMessageList의 null 체크
=> 🐛 [Fix] 채팅방 새로 생성 시 채팅방 영역 렌더링 안되는 버그 수정

public/matching/scripts/socket.js, socket/apis/matchApi.js, socket/emitters/matchingEmitter.js, socket/handlers/matching/matchingHandler/matchingFoundHandler.js, socket/handlers/matching/matchingSocketListeners.js
매칭 status 변경할 때 gameMode 변경하는거 추가, client에서 matching-fail 소켓 이벤트 받을 때 matchingSuccessCallback 취소하기
- matching API request 에 gameMode 추가
- client에서 matching-fail 시 matchingSuccessCallback callback 취소
=> [Fix/69] 매칭 관련 수정

app/controller/socketController.js, app/routers/index.js, socket/emitters/chatEmitter.js
시스템 메시지 전송 event emit API 구현
- chatEmitter 메소드 추가
- 시스템 메시지 전송 event emit API 구현
=> [Feat/76] 시스템 메시지 전송 event emit API 구현

app/app.js, public/matching/scripts/socket.js, socket/handlers/matching/matchingSocketListeners.js
matching-quit socket event 제대로 작동하는지 확인하기
- 매칭 시 화면에 quit 버튼 추가
- quit 버튼 누를 시 서버로 socket event 발생
=> [Feat/80] matching-quit socket event 제대로 작동하는지 확인하기

socket/socket.js
disconnect 시 매칭 관련 수정
- disconnect  매칭 관련 작업
=> [Feat/82] disconnect 시 매칭 관련 수정

app/controller/socketController.js, public/scripts/socket.js, socket/emitters/chatEmitter.js
manner-system-message 이벤트 분리
- manner-system-message 이벤트 분리
=> ♻️ [Refactor] manner-system-message 이벤트 분리

app/app.js, index.js, socket/socket.js
프론트 도메인 CORS 허용
- 프론트 도메인 CORS 허용
=> [Feat/90] 프론트 도메인 CORS 허용

common/winston.js, package-lock.json, package.json
winston 모듈 설정
- winston 의존성 추가
- logger 메소드 구현
=> [Refactor/93] winston 모듈 설정

socket/handlers/matching/matchingSocketListeners.js
matching-found-sender emit 시 딜레이 주기
- matching-found-sender emit 시 딜레이 주기
=> [Fix/10] matching-found-sender emit 시 딜레이 주기

socket/apis/matchApi.js
게임 스타일 관련 에러 해결 
- 게임스타일 리스트 만들 때 필터 추가
=> 🐛[fix] 게임 스타일 에러 해결

socket/handlers/matching/matchingSocketListeners.js
matching-found-sender emit 시 2초 딜레이 rollback
- matching-found-sender emit 시 2초 딜레이 rollback
=> [FIx/101] matching-found-sender emit 시 2초 딜레이 rollback

app/controller/socketController.js, socket/emitters/chatEmitter.js
manner-system-message에 timestamp 추가
- manner-system-message에 timestamp 추가
- manner-system-message에 timestamp 추가
=> [Feat/105] manner-system-message에 timestamp 추가

.github/workflows/deploy.yml, dockerfile
=> [Cicd/113] 서버 timezone 설정

.github/workflows/deploy.yml
=> [Cicd/117] 로그 저장 경로 마운트 설정

app/app.js
=> [Feat/119] health check API 구현

socket/handlers/matching/matchingHandler/matchingFailHandler.js
> matching-quit 수정, matching-not-found 개발
=> [Feat/125] matching-quit 수정, matching-not-found 개발

public/scripts/matching/matchingSocketEventHandlers.js, socket/emitters/matchingEmitter.js, socket/handlers/matching/matchingHandler/matchingFailHandler.js, socket/handlers/matching/matchingHandler/matchingSuccessHandler.js, socket/handlers/matching/matchingSocketListeners.js, socket/socket.js
matching-reject, matching-fail 개발
> 여기에 작성해주세요.
=> [Feat/127] matching-reject, matching-fail 개발

public/scripts/matching/matchingSocketEventHandlers.js, socket/handlers/matching/matchingHandler/matchingSuccessHandler.js
>  matching-found-success 예외처리 추가
=> [Feat/135] matching-found-success 예외처리 추가

app/app.js, public/scripts/matching/matchingSocketEventHandlers.js, public/scripts/socket.js, socket/handlers/matching/matchingHandler/matchingManager.js, socket/handlers/matching/matchingHandler/matchingRequestHandler.js
=> [Feat/137] matching solo, free Tier 추가

app/app.js, public/scripts/matching/matchingEventListeners.js, public/scripts/matching/matchingSocketEventHandlers.js
> matching wantP list로 받도록 프론트 테스트 코드 작성
=> [Feat/139] matching wantP list로 받도록 프론트 테스트 코드 작성

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-qa.yml, Dockerfile-dev, Dockerfile-prod, Dockerfile-qa, app/app.js, common/winston.js, index.js, socket/socket.js
=> [Ci/145] 운영/개발/QA 환경 분리

app/controller/FriendOnlineController.js, app/routers/index.js
=> [Feat/149] 친구 온라인 이벤트 API 구현

public/scripts/matching/matchingSocketEventHandlers.js, socket/handlers/matching/matchingHandler/matchingFailHandler.js, socket/handlers/matching/matchingHandler/matchingManager.js
=> [Fix/151] 초기화 에러 수정
